#ifndef FSMDLOADER_H__
#define FSMDLOADER_H__

enum
{
	_SMD_DUMMY_FIRST_ = 1000,

	Fsmdloader,
	SMD_LOADER_SCALE,
	SMD_LOADER_ROTATE,
	SMD_LOADER_SWAPYZ,
	SMD_IMPORT_ANIMATION,
	SMD_IMPORT_QC,
	SMD_IMPORT_MESH,
	SMD_IMPORT_TOP_NULL,
	SMD_IMPORT_SKELETON_JOINT,
	SMD_IMPORT_MESH_WELD,
	SMD_IMPORT_MESH_WELD_TOLERANCE,
	SMD_IMPORT_MESH_MATERIALS,
	SMD_IMPORT_MESH_UV,
	SMD_IMPORT_MESH_NORMALS,
	SMD_IMPORT_MESH_WEIGHTS,
	SMD_IMPORT_MATERIAL_ROOT,
	SMD_IMPORT_IK,
	SMD_IMPORT_IK_ORIENTATION,
	IK_CAMERA,
	IK_XY,
	IK_ZY,
	IK_XZ,
	SMD_CACHE_MEMORY,
	SMD_MEMORY_USAGE,
	SMD_FLUSH_CACHE,
	SMD_MAT_FILETYPE,
	MATFT_VTF,
	MATFT_TGA,
	MATFT_CUSTOM,

	// Hidden
	SMD_CUSTOM_ROOT_NAME,

	_SMD_DUMMY_LAST_
};

#endif