#ifndef FSMDLOADER_H__
#define FSMDLOADER_H__

enum
{
	_DUMMY_FIRST_ = 1000,

	Fsmdloader,
	SMD_LOADER_SCALE,
	SMD_IMPORT_ANIMATION,
	SMD_IMPORT_QC,
	SMD_IMPORT_QC_BODYGROUP,
	BODYGROUP_ALL,
	BODYGROUP_ASK,
	SMD_IMPORT_MESH,
	SMD_IMPORT_MESH_WELD,
	SMD_IMPORT_MESH_WELD_TOLERANCE,
	SMD_IMPORT_MESH_MATERIALS,
	SMD_IMPORT_MESH_UV,
	SMD_IMPORT_MESH_NORMALS,
	SMD_IMPORT_MESH_WEIGHTS,
	SMD_IMPORT_MATERIAL_ROOT,
	SMD_IMPORT_IK,
	SMD_IMPORT_IK_ORIENTATION,
	IK_CAMERA,
	IK_XY,
	IK_ZY,
	IK_XZ,

	_DUMMY_LAST_
};

#endif