#ifndef ST_C4D_SYMBOLS_H
#define ST_C4D_SYMBOLS_H

enum
{
	_FIRST_ELEMENT_ = 10000,

	// Globals
	IDS_PLUGIN_NAME,
	IDS_UPDATE_AVAIL_0,
	IDS_UPDATE_AVAIL_1,
	IDS_NEW_INSTALL,
	IDS_CRITICAL_ERROR,

	// About Dialog
	ABOUTDLG,
	IDS_PLUGIN_VERSION,
	IDC_ABOUT_DIALOG_BANNER,
	IDS_TRANSLATION_AUTHOR,
	IDS_TRANSLATION_WEBSITE,
	IDC_PAYPAL,
	IDC_STEAM,
	IDT_TAB_GROUP,
	IDT_ABOUT,
	IDT_SETTINGS,
	IDC_SAVE_SETTINGS,
	IDS_SETTINGS_SAVED,

	IDC_AUTO_UPDATE,

	// VTF Import/Export
	IDS_VTF,

	// SMD Import
	IDS_SMD,
	IDS_NO_MAT_DIR,
	IDS_NO_MAT,
	IDS_NO_QC,
	IDS_LOADED_FILE,
	IDS_IN,
	IDS_BAD_REBUILD,
	IDS_CACHE_FLUSHED,
	IDS_FLUSHING_CACHE,

	// Source Animation Tag
	IDS_SOURCE_ANIMATION,

	// End of symbol definition
	_DUMMY_ELEMENT_
};

#endif