#ifndef FQCLOADER_H__
#define FQCLOADER_H__

enum {
  QC_LOADER_IMPORT_UNDER_NULL = 1200,
  QC_LOADER_SCALE,
  QC_LOADER_ROTATE,
  QC_LOADER_IMPORT_SKELETON,
  QC_LOADER_IMPORT_ANIMATION,
  QC_LOADER_IMPORT_MESH,
  QC_LOADER_IMPORT_WEIGHTS,
  QC_LOADER_MATERIAL_PATH,
  SOURCETYPE_NONE,
  SOURCETYPE_VMF_VTF,
  SOURCETYPE_VMF_TGA,
  SOURCETYPE_VMF_OTHER,
  QC_LOADER_SOURCETYPE,
  QC_MATERIAL_EXTENSION,
  QC_LOADER_IMPORT_IK,
  QC_LOADER_IMPORT_PHYSICS
};

#endif // !FQCLOADER_H__