#ifndef FQCLOADER_H__
#define FQCLOADER_H__

enum
{
	_QC_DUMMY_FIRST_ = 1000,

    Fqcloader,
    QC_LOADER_IMPORT_UNDER_NULL,
    QC_LOADER_SCALE,
    QC_LOADER_ROTATE,
    QC_LOADER_IMPORT_SKELETON,
    QC_LOADER_IMPORT_MESH,
    QC_LOADER_IMPORT_WEIGHTS,
    QC_LOADER_IMPORT_MATERIALS,
    QC_LOADER_MATERIAL_PATH
	
};

#endif // !FQCLOADER_H__