#ifndef FSMDLOADER_H__
#define FSMDLOADER_H__

enum
{
    SMD_LOADER_SCALE = 1100,
    SMD_LOADER_ROTATE,
    SMD_LOADER_IMPORT_UNDER_NULL,
    SMD_LOADER_IMPORT_ANIMATION,
    SMD_LOADER_IMPORT_MESH,
    SMD_LOADER_IMPORT_WEIGHTS,
    SMD_LOADER_IMPORT_SKELETON
};

#endif // !FSMDLOADER_H__