#ifndef FSMDLOADER_H__
#define FSMDLOADER_H__

enum
{
	_SMD_DUMMY_FIRST_ = 1000,
	
    Fsmdloader,
    SMD_LOADER_SCALE,
    SMD_LOADER_ROTATE,
    SMD_LOADER_IMPORT_UNDER_NULL,
    SMD_LOADER_IMPORT_ANIMATION,
    SMD_LOADER_IMPORT_MESH,
    SMD_LOADER_IMPORT_WEIGHTS
};

#endif // !FSMDLOADER_H__