#ifndef SOURCETOOLS_C4D_SYMBOLS_H__
#define SOURCETOOLS_C4D_SYMBOLS_H__

enum
{
	_FIRST_ELEMENT_ = 10000,
	S_BUILDINGFILE,
	S_PARSINGFILE,
	S_BUILDINGFILE_SUB,
	S_PARSINGFILE_SUB,
	S_INVALID_MATERIAL_PATH,
	S_PARSE_ERROR
};

#endif // !SOURCETOOLS_C4D_SYMBOLS_H__