#ifndef FALEMBICIMPORT_H__
#define FALEMBICIMPORT_H__

enum
{
	ABCIMPORT_GROUP				= 999,
	ABCIMPORT_STR_GENERAL = 1000,
	ABCIMPORT_VISIBILITY,
	ABCIMPORT_STR_OPTIONS,
	ABCIMPORT_NORMALS,
	ABCIMPORT_UVS,
	ABCIMPORT_FACESETS,
	ABCIMPORT_CAMERAS,
	ABCIMPORT_SUBDS,
	ABCIMPORT_CURVES,
	ABCIMPORT_POINTS,
	ABCIMPORT_SCALE,
	ABCIMPORT_STR_ANIMATION,
	ABCIMPORT_FPS,
	ABCIMPORT_STARTFRAME,
	ABCIMPORT_NOSTARTFRAME,
	ABCIMPORT_CURVES_AS,
	ABCIMPORT_CURVES_AS_SPLINES,
	ABCIMPORT_CURVES_AS_HAIR,
	ABCIMPORT_POINTS_AS,
	ABCIMPORT_POINTS_AS_TPARTICLES,
	ABCIMPORT_POINTS_AS_GEOMETRY,
	ABCIMPORT_COLORMAPS,
	ABCIMPORT_SDSWEIGHTS
};

#endif // FALEMBICIMPORT_H__


