#ifndef FOKINOIMPORT_H__
#define FOKINOIMPORT_H__

enum
{
	OKINOIMPORT_STR_OPTIONS = 1000,
	OKINOSHOW_SETTINGS,
	OKINOSHOW_EXPORT_SETTINGS,
	OKINOCLEAR_TEMP,
	OKINO_KEEP_IN_MEM,
	OKINOIMPORT_FILTER_LIST,
	OKINOINTERMEDIATE_LWS_OPTIONS,
	OKINOINTERMEDIATE_FBX_OPTIONS,
	OKINOIMPORT_FILTER_CONTAINER,

	FokinoimportGroup = 9999
};

#endif // FOKINOIMPORT_H__


