#ifndef OBONE_H__
#define OBONE_H__

enum
{
	// object properties
	ID_FIXED									= 820,
	BONEOBJECT_FUNCTION				= 1000, // LONG
		BONEFUNCTION_R   = 0,
		BONEFUNCTION_R2  = 1,
		BONEFUNCTION_R4  = 2,
		BONEFUNCTION_R6  = 3,
		BONEFUNCTION_R8  = 4,
		BONEFUNCTION_R10 = 5,
	BONEOBJECT_LIMITRANGE			= 1001, // BOOL
	BONEOBJECT_SCALESTRENGTH	= 1002, // BOOL
	BONEOBJECT_MINRANGE				= 1003, // REAL
	BONEOBJECT_MAXRANGE				= 1004, // REAL
	BONEOBJECT_STRENGTH				= 1005, // REAL
	BONEOBJECT_LENGTH					= 1006, // REAL
	BONEOBJECT_FIXPOSITION		= 1007, // VECTOR
	BONEOBJECT_FIXSCALE				= 1008, // VECTOR
	BONEOBJECT_FIXROTATION		= 1009, // VECTOR
	BONEOBJECT_FIXLENGTH			= 1010, // REAL
	BONEOBJECT_NULL           = 1011, // BOOL
	BONEOBJECT_FIXED          = 1012, // BOOL

	BONEOBJECT_FIX            = 1013, // BUTTON
	BONEOBJECT_FIXCHILDS      = 1014, // BUTTON
	BONEOBJECT_FIXCHAIN       = 1015, // BUTTON
	BONEOBJECT_NEWBONES				= 1017, // BOOL: new bone algo
	BONEOBJECT_VERTEXMAPMODE	= 1018, // BOOL: TRUE shows the new vertexmap mode for FBX (absolute maps)

	GROUP_FIN                 = 2000,
	BONEOBJECT_FIN_SHOW       = 2001, // bool
	BONEOBJECT_FIN_S_SIZE     = 2002, // vector
	BONEOBJECT_FIN_S_OFF      = 2003, // vector
	BONEOBJECT_FIN_E_SIZE     = 2004, // vector
	BONEOBJECT_FIN_E_OFF      = 2005, // vector

	BONE_DUMMY
};

#endif // OBONE_H__
