#ifndef OMOGRAPH_CLONER_H__
#define OMOGRAPH_CLONER_H__

enum
{
	MGCLONER_MODE					= 1020,
	MGCLONER_MODE_CLUSTER = 0,
	MGCLONER_MODE_ITERATE,
	MGCLONER_MODE_RANDOM,
	MGCLONER_MODE_BLEND,
	MGCLONER_MODE_SORT,
	MGCLONER_FIX_TEXTURE_OFF = 0,
	MGCLONER_FIX_TEXTURE_STRAIGHT,
	MGCLONER_FIX_TEXTURE_ALTX,
	MGCLONER_FIX_TEXTURE_ALTY,
	MGCLONER_ANIMATIONMODE_PLAY = 0,
	MGCLONER_ANIMATIONMODE_LOOP,
	MGCLONER_ANIMATIONMODE_FIXED,
	MGCLONER_ANIMATIONMODE_FIXEDLOOP,
	MGCLONER_FIX_CLONES					= 1021,
	MGCLONER_SEED								= 1022,
	MGCLONER_FIX_TEXTURE				= 1023,
	MGCLONER_ANIMATIONMODE			= 1024,
	MGCLONER_VOLUMEINSTANCES		=	1025
};
#endif // OMOGRAPH_CLONER_H__
