#ifndef TEDGESELECTION_H__
#define TEDGESELECTION_H__

enum
{
	EDGESELECTIONTAG_COMMAND1 = 1000, // virtual ID
	EDGESELECTIONTAG_COMMAND2 = 1001,
	EDGESELECTIONTAG_COMMAND3 = 1002,
	EDGESELECTIONTAG_COMMAND4 = 1003,
	EDGESELECTIONTAG_COMMAND5 = 1004,
	EDGESELECTIONTAG_COMMAND6 = 1005
};

#endif // TEDGESELECTION_H__
