#ifndef TRIBCONTAINER_H__
#define TRIBCONTAINER_H__

enum
{
	RIBCONTAINER_POS					= 10000,
		RIBCONTAINER_POS_BEFORE			= 0,
		RIBCONTAINER_POS_AFTER			= 1,
		RIBCONTAINER_POS_REPLACE		= 2,
	RIBCONTAINER_COFFEE					= 10001,
	RIBCONTAINER_ASCII					= 10002,
	RIBCONTAINER_ENABLED				= 10003,

	RIBCONTAINER_DUMMYBUTTON			= 20000,
	RIBCONTAINER_DUMMYSTRING			= 20001
};

#endif // TRIBCONTAINER_H__
