#ifndef TVERTEXCOLOR_H__
#define TVERTEXCOLOR_H__

enum
{
		ID_VERTEXCOLOR_VERTEXCOLORMODE = 1001,
			ID_VERTEXCOLOR_VERTEXCOLORMODE_VERTEX = 0,
			ID_VERTEXCOLOR_VERTEXCOLORMODE_POLYGON = 1,
		ID_VERTEXCOLOR_ALPHAMODE = 1000
};

#endif // TVERTEXCOLOR_H__

