#ifndef VPPREVIEWHARDWARE_H__
#define VPPREVIEWHARDWARE_H__

enum
{
	VP_PREVIEWHARDWARE_ENHANCEDOPENGL								=	1000,
	VP_PREVIEWHARDWARE_TRANSPARENCY  = 1001,
	VP_PREVIEWHARDWARE_SHADOW				= 1002,
	VP_PREVIEWHARDWARE_POSTEFFECT		= 1003,
	VP_PREVIEWHARDWARE_NOISE					= 1004,
	VP_PREVIEWHARDWARE_ANTIALIASING	= 1005,
		VP_PREVIEWHARDWARE_ANTIALIASING_NONE	= 0,
	VP_PREVIEWHARDWARE_TESSELLATION = 1006,
	VP_PREVIEWHARDWARE_SSAO = 1007,
	VP_PREVIEWHARDWARE_REFLECTIONS = 1008,

	VP_PREVIEWHARDWARE_DUMMY
};

#endif // VPPREVIEWHARDWARE_H__
