DIALOG ABOUTDLG
{
	NAME DIALOG_TITLE;

	TAB IDT_TAB_GROUP
	{
		SELECTION_TABS;
		SCALE_H; SCALE_V;

		GROUP IDT_ABOUT
		{
			NAME S_ABOUT_TAB;
			COLUMNS 1;
			SCALE_H; SCALE_V;
			SPACE 0, 0;
			SIZE -400, -270;

			USERAREA IDC_ABOUT_DIALOG_BANNER { SCALE_H; CENTER_H; };

			STATICTEXT { NAME S_PLUGIN_NAME; SCALE_H; CENTER_H; }
			STATICTEXT IDS_PLUGIN_VERSION { NAME S_PLUGIN_VERSION; SCALE_H; CENTER_H; }
			STATICTEXT { SIZE 0, 10; SCALE_H; }
			STATICTEXT { NAME S_AUTHOR; SCALE_H; CENTER_H; }
			STATICTEXT { NAME S_AUTHOR_2; SCALE_H; CENTER_H; }
			HYPERLINK { SCALE_H; CENTER_H; STATIC_TEXT L_TWITTER; LINK_DEST L_TWITTER; IS_LINK; }
			STATICTEXT { SIZE 0, 10; SCALE_H; }
			STATICTEXT IDS_TRANSLATION_AUTHOR { NAME TRANSLATION_AUTHOR; SCALE_H; CENTER_H; }
			HYPERLINK IDS_TRANSLATION_WEBSITE { SCALE_H; CENTER_H; STATIC_TEXT TRAN_LINK; LINK_DEST TRAN_LINK; IS_LINK; }

			SEPARATOR { SCALE_H; }
			GROUP
			{
				COLUMNS 2; ROWS 1;
				SCALE_H; SCALE_V;
				CENTER_H; CENTER_V;
			
				GROUP
				{
					COLUMNS 1;
					SCALE_V; CENTER_V; CENTER_H;
					STATICTEXT { NAME S_DONATIONS_0; SCALE_H; CENTER_H; }
					STATICTEXT { NAME S_DONATIONS_1; SCALE_H; CENTER_H; }
					STATICTEXT { NAME S_DONATIONS_2; SCALE_H; CENTER_H; }
				}

				GROUP
				{
					COLUMNS 1;
					SCALE_V; CENTER_V; CENTER_H;
					SIZE -140, 0;
					USERAREA IDC_PAYPAL { SCALE_H; CENTER_H; }
					USERAREA IDC_STEAM { SCALE_H; CENTER_H; }
				}
			}
		}

		GROUP IDT_SETTINGS
		{
			NAME S_SETTINGS_TAB;
			COLUMNS 1;
			SCALE_H; SCALE_V;
			BORDERSIZE 10, 10, 10, 10;

			GROUP
			{
				NAME S_GENERAL;
				BORDERSTYLE BORDER_GROUP_TOP;
				COLUMNS 1;

				CHECKBOX IDC_AUTO_UPDATE
				{
					NAME S_AUTO_UPDATE;
				}
			}

			BUTTON IDC_SAVE_SETTINGS { SCALE_H; SCALE_V; NAME S_SAVE_SETTINGS; ALIGN_RIGHT; ALIGN_BOTTOM; }
		}
	}
}