DIALOG ABOUTDLG
{
	NAME DIALOG_TITLE;
	SCALE_H; SCALE_V;

	GROUP
	{
		SIZE -300, -200;
		COLUMNS 1;
		SCALE_H; SCALE_V;
		SPACE 0, 0;

		USERAREA IDC_ABOUT_DIALOG_BANNER { SCALE_H; CENTER_H; };

		STATICTEXT { NAME S_PLUGIN_NAME; SCALE_H; CENTER_H; }
		STATICTEXT IDS_PLUGIN_VERSION { NAME S_PLUGIN_VERSION; SCALE_H; CENTER_H; }
		STATICTEXT { SIZE 0, 10; SCALE_H; }
		STATICTEXT { NAME S_AUTHOR; SCALE_H; CENTER_H; }
		STATICTEXT { NAME S_AUTHOR_2; SCALE_H; CENTER_H; }
		HYPERLINK { SCALE_H; CENTER_H; STATIC_TEXT L_TWITTER; LINK_DEST L_TWITTER; IS_LINK; }
	}
}